// R5H isolated payment interaction module. Demo records only; no Finance or bank writes.
// The existing hardened Finance engine remains the production authority.
export function createPaymentTask({onChange=()=>{}}={}) {
  const TOTAL=8000;
  const initial=()=>({entries:[],reports:[],draft:{amount:'80.00',reference:'',date:'',note:''},confirmed:false,events:[{title:'Quote accepted',detail:'Q-1048 · £80.00 locked · demo'}]});
  let state=initial(), mode='home', selected=null, root=null, error='';
  const money=n=>'£'+(n/100).toFixed(2);
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const received=()=>state.entries.filter(e=>e.status==='verified').reduce((n,e)=>n+e.amount,0);
  const pending=()=>state.entries.filter(e=>e.status==='pending').reduce((n,e)=>n+e.amount,0);
  const remaining=()=>Math.max(0,TOTAL-received());
  const available=()=>Math.max(0,remaining()-pending());
  const parse=s=>{const v=String(s).trim();if(!/^\d+(?:\.\d{1,2})?$/.test(v))return null;const n=Math.round(Number(v)*100);return Number.isSafeInteger(n)?n:null;};
  const log=(title,detail)=>state.events.unshift({title,detail});
  const status=()=>state.confirmed?'Received':pending()?'Review needed':remaining()===0?'Ready to reconcile':received()?'Part paid':state.reports.some(r=>r.status==='reported')?'Payment reported':'Awaiting';
  const snapshot=()=>({total:TOTAL,received:received(),pending:pending(),remaining:remaining(),confirmed:state.confirmed,status:status(),events:state.events.length});
  const emit=()=>onChange(snapshot());
  const button=(label,act,primary=false)=>`<button type="button" class="pm-btn ${primary?'pm-primary':''}" data-pm="${act}">${label}</button>`;
  const title=(label,tone='neutral')=>`<h2 class="pm-heading" data-tone="${tone}"><span class="pm-dot" aria-hidden="true"></span>${label}</h2>`;
  const field=(label,name,value='',type='text',required=false)=>`<label class="pm-field"><span>${label}</span><input name="${name}" type="${type}" value="${escape(value)}" ${required?'required':''} ${type==='text'?'maxlength="100"':''} ${name==='amount'?'inputmode="decimal"':''}></label>`;
  const notice=()=>error?`<p class="pm-error" role="alert">${escape(error)}</p>`:'';
  function paint(){if(!root)return;const s=snapshot();root.innerHTML=`<div class="pm-head"><div><h2>Payment</h2><p>Bank transfer · Q-1048</p></div><span class="pm-status ${s.confirmed?'pm-success':''}">${escape(s.status)}</span></div><div class="pm-money"><div><span>Amount due</span><strong>${money(TOTAL)}</strong></div><div><span>Received</span><strong>${money(s.received)}</strong></div></div><div class="pm-work" id="pm-work"></div><div id="pm-activity"></div><details class="pm-details"><summary>Accepted quote</summary><div class="pm-fact"><span>Quote</span><strong>Q-1048</strong></div><div class="pm-fact"><span>Items</span><strong>BPC-157 10mg × 2</strong></div><div class="pm-fact"><span>Accepted total</span><strong>£80.00 · locked</strong></div></details>`;paintWork();paintActivity();emit();}
  function paintWork(){const area=root.querySelector('#pm-work');if(!area)return;const due=remaining(),pend=pending();
    if(state.confirmed){area.innerHTML=`<div class="pm-complete">${title('Payment received','success')}<p>£80.00 reconciled · Ready for fulfilment</p></div>`;return;}
    if(mode==='entry'){area.innerHTML=`<section class="pm-focus">${title('Record bank transfer')}<p>Enter the amount shown by the bank. Saving evidence does not confirm receipt.</p><form data-pm-form="entry">${field('Amount received (£)','amount',state.draft.amount,'text',true)}${field('Bank transaction reference','reference',state.draft.reference,'text',true)}${field('Date received','date',state.draft.date,'date',true)}<label class="pm-field"><span>Evidence note · optional</span><textarea name="note" rows="2" maxlength="500">${escape(state.draft.note)}</textarea></label>${notice()}<div class="pm-actions"><button class="pm-btn pm-primary" type="submit">Save evidence</button>${button('Cancel','cancel')}</div></form></section>`;return;}
    if(mode==='report'){area.innerHTML=`<section class="pm-focus">${title('Customer says paid','attention')}<p>Record the customer's claim. It does not increase money received.</p><form data-pm-form="report">${field('Amount reported (£)','amount',(due/100).toFixed(2),'text',true)}${field('Date reported','date','','date',true)}${field('Reference supplied · optional','reference') }<label class="pm-field"><span>Customer message / note</span><textarea name="note" rows="2" maxlength="500"></textarea></label>${notice()}<div class="pm-actions"><button class="pm-btn pm-primary" type="submit">Save report</button>${button('Cancel','cancel')}</div></form></section>`;return;}
    if(mode==='review'){const e=state.entries.find(x=>x.id===selected&&x.status==='pending');if(!e){mode='home';paintWork();return;}area.innerHTML=`<section class="pm-focus">${title('Review bank evidence','attention')}<div class="pm-review-amount">${money(e.amount)}</div><p>${escape(e.reference)} · ${escape(e.date)}</p><label class="pm-check"><input type="checkbox" id="pm-bank-check"><span>I independently checked the bank record and confirmed this exact payment.</span></label><label class="pm-field"><span>Decision note</span><textarea id="pm-review-note" rows="2" maxlength="500" placeholder="Required for rejection"></textarea></label>${notice()}<div class="pm-actions">${button('Confirm received','verify',true)}${button('Reject evidence','reject')}${button('Cancel','cancel')}</div></section>`;return;}
    if(mode==='reconcile'&&due===0&&!pend){area.innerHTML=`<section class="pm-focus">${title('Final reconciliation','success')}<p>£80.00 of bank evidence has been confirmed.</p><label class="pm-check"><input type="checkbox" id="pm-final-check"><span>I have reviewed the evidence and confirm the accepted total is fully reconciled.</span></label>${notice()}<div class="pm-actions">${button('Confirm reconciliation','finish',true)}${button('Cancel','cancel')}</div></section>`;return;}
    if(pend){area.innerHTML=`<section class="pm-task">${title('Evidence awaiting review','attention')}<p>${money(pend)} awaiting bank check · ${money(due)} remaining</p><div class="pm-actions">${button('Review evidence','review-next',true)}${available()>0?button('Add payment','entry'):''}</div></section>`;return;}
    if(due===0){area.innerHTML=`<section class="pm-task">${title('Ready to reconcile','attention')}<p>Full amount received. Final reconciliation is still required.</p><div class="pm-actions">${button('Review reconciliation','reconcile',true)}</div></section>`;return;}
    area.innerHTML=`<section class="pm-task">${title('Bank transfer',received()?'attention':'neutral')}<div class="pm-balance"><span>Outstanding balance</span><strong>${money(due)}</strong></div>${received()?'<p>Additional payment required.</p>':'<p>No payment received yet.</p>'}<div class="pm-actions">${button('Record payment','entry',true)}${button('Customer says paid','report')}</div></section>`;
  }
  function paintActivity(){const area=root.querySelector('#pm-activity');const rows=[...state.entries.map(e=>({kind:'entry',data:e})),...state.reports.map(r=>({kind:'report',data:r}))];if(!rows.length){area.innerHTML='';return;}area.innerHTML=`<section class="pm-activity">${title('Payment activity',pending()?'attention':'neutral')}<div class="pm-entries">${rows.map(item=>{const e=item.data;const report=item.kind==='report';const label=report?'reported':e.status==='verified'?'received':e.status==='pending'?'awaiting review':'rejected';return `<div class="pm-entry"><div><strong>${money(e.amount)} ${label}</strong><small>${escape(e.date)}${e.reference?' · '+escape(e.reference):''}</small>${e.note?'<p>'+escape(e.note)+'</p>':''}${e.reviewNote?'<p>'+escape(e.reviewNote)+'</p>':''}</div><div>${e.status==='pending'?button('Review','review:'+e.id):`<span class="pm-small-status ${e.status==='verified'?'pm-success':''}">${report?(e.status==='matched'?'Matched':'Reported'):label}</span>`}</div></div>`;}).join('')}</div></section>`;}
  function invalid(message){error=message;paintWork();}
  function setMode(next){mode=next;error='';paintWork();}
  function saveEvidence(form){const d=Object.fromEntries(new FormData(form));const amount=parse(d.amount);if(amount===null||amount<=0)return invalid('Enter a valid amount greater than zero.');if(!d.reference.trim())return invalid('Enter the bank transaction reference.');if(!d.date)return invalid('Select the date received.');if(amount>available())return invalid('Amount exceeds the balance not already covered by pending evidence.');if(state.entries.some(e=>e.reference.toLowerCase()===d.reference.trim().toLowerCase()))return invalid('This reference is already recorded. Review the existing evidence.');state.entries.push({id:String(state.entries.length+1),amount,reference:d.reference.trim(),date:d.date,note:d.note.trim(),status:'pending',reviewNote:''});log('Payment evidence recorded',money(amount)+' · '+d.reference.trim()+' · Awaiting verification');state.draft={amount:(available()/100).toFixed(2),reference:'',date:'',note:''};mode='home';error='';paint();}
  function saveReport(form){const d=Object.fromEntries(new FormData(form));const amount=parse(d.amount);if(amount===null||amount<=0)return invalid('Enter a valid reported amount.');if(!d.date)return invalid('Select the date reported.');state.reports.push({id:'R'+(state.reports.length+1),amount,date:d.date,reference:d.reference.trim(),note:d.note.trim(),status:'reported',match:''});log('Customer reported payment',money(amount)+' · Not bank-confirmed');mode='home';paint();}
  function act(action){if(action==='cancel'){setMode('home');return;}if(action==='entry'){state.draft.amount=(available()/100).toFixed(2);setMode('entry');return;}if(action==='report'||action==='reconcile'){setMode(action);return;}if(action.startsWith('review:')){selected=action.slice(7);setMode('review');return;}if(action==='review-next'){selected=state.entries.find(e=>e.status==='pending')?.id;setMode('review');return;}if(action==='verify'||action==='reject'){const e=state.entries.find(x=>x.id===selected&&x.status==='pending');if(!e)return;const note=root.querySelector('#pm-review-note')?.value.trim()||'';if(action==='verify'){if(!root.querySelector('#pm-bank-check')?.checked)return invalid('Confirm the independent bank check first.');if(e.amount>remaining())return invalid('This would exceed the accepted total.');e.status='verified';e.reviewNote=note;const matches=state.reports.filter(r=>r.status==='reported'&&r.amount===e.amount&&(r.reference.toLowerCase()===e.reference.toLowerCase()||!r.reference));if(matches.length===1){matches[0].status='matched';matches[0].match=e.reference;}log('Payment received',money(e.amount)+' · '+e.reference+' · Bank checked by demo operator');}else{if(!note)return invalid('Record why this evidence is being rejected.');e.status='rejected';e.reviewNote=note;log('Evidence rejected',e.reference+' · '+note);}mode='home';paint();return;}if(action==='finish'){if(remaining()!==0||pending())return invalid('Full payment and evidence review are required.');if(!root.querySelector('#pm-final-check')?.checked)return invalid('Confirm reconciliation first.');state.confirmed=true;log('Payment reconciled',money(TOTAL)+' fully confirmed · Demo operator');mode='home';paint();}}
  function mount(element){root=element;root.classList.add('payment-module');root.addEventListener('click',e=>{const b=e.target.closest('[data-pm]');if(b&&root.contains(b))act(b.dataset.pm);});root.addEventListener('submit',e=>{const form=e.target.closest('[data-pm-form]');if(!form||!root.contains(form))return;e.preventDefault();form.dataset.pmForm==='entry'?saveEvidence(form):saveReport(form);});paint();return api;}
  function scenario(name){state=initial();mode='home';selected=null;error='';if(name==='partial'||name==='complete'){state.entries.push({id:'1',amount:3000,reference:'DEMO-BANK-030',date:'2026-09-08',note:'Scenario fixture',status:'verified',reviewNote:'Bank checked by demo operator'});log('Payment received','£30.00 · DEMO-BANK-030 · Demo fixture');}if(name==='complete'){state.entries.push({id:'2',amount:5000,reference:'DEMO-BANK-050',date:'2026-09-08',note:'Scenario fixture',status:'verified',reviewNote:'Bank checked by demo operator'});state.confirmed=true;log('Payment reconciled','£80.00 fully confirmed · Demo fixture');}paint();}
  const api={mount,scenario,snapshot,reset:()=>scenario('empty'),getState:()=>structuredClone(state)};return api;
}
