import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createQuoteDomainAdapter} from '../finance-operator-v2-job-ready-quote-proof/quote-domain-adapter.js';
const base=()=>({id:'Q-1',isQuote:true,readOnly:false,quoteStatus:'Quote to send',approvalCurrent:false,quoteApproval:null,acceptedSnapshot:null,commercialLock:null,convertedOrderId:'',messagePrepared:false,messageCurrent:false,messageFingerprint:'message-fp',handoffEvidence:null});
function harness(){
 let state=base(),saved=null;const calls=[];
 const port={read:()=>state,readSaved:()=>saved,list:()=>saved?[saved]:[],async command(name,payload){calls.push(name);switch(name){
 case 'newQuote':state=base();return true;
 case 'open':state={...state,id:payload};return true;
 case 'saveDraft':saved=structuredClone({...state,confirmation:saved?.confirmation||'No'});return true;
 case 'approve':state.quoteApproval={fingerprint:'fp1'};state.approvalCurrent=true;saved=structuredClone(state);return true;
 case 'prepareMessage':state.messagePrepared=true;state.messageCurrent=true;return true;
 case 'prepareHandoff':state.handoffEvidence={channel:payload,fingerprint:state.messageFingerprint};return true;
 case 'recordSent':state.quoteStatus='Quote sent / waiting customer';state.confirmation='Yes';saved=structuredClone(state);return true;
 case 'recordAcceptance':state.acceptedSnapshot={total:80,quoteRef:state.id};state.quoteStatus='Customer replied / ready to convert';saved=structuredClone(state);return true;
 case 'convert':state={...state,id:'O-1',isQuote:false,sourceQuoteId:'Q-1',commercialLock:state.acceptedSnapshot};return true;
 case 'saveConvertedOrder':{const source=saved;source.convertedOrderId=state.id;saved=structuredClone(state);savedSource=source;return true;}
 default:throw Error('Unexpected command '+name);
 }}};
 let savedSource=null;
 port.readSaved=id=>id==='Q-1'&&savedSource?savedSource:(saved?.id===id?saved:null);
 return{adapter:createQuoteDomainAdapter(port),calls,set:s=>{state=s},get:()=>state,save:s=>{saved=s}};
}
test('draft saving delegates to authority and retains source identity',async()=>{const h=harness();await h.adapter.saveDraft();assert.deepEqual(h.calls,['saveDraft']);assert.equal(h.adapter.read().id,'Q-1')});
test('accepted or read-only records cannot be edited',async()=>{const h=harness();h.set({...base(),readOnly:true});await assert.rejects(()=>h.adapter.saveDraft(),/read-only/);h.set({...base(),acceptedSnapshot:{total:80}});await assert.rejects(()=>h.adapter.approve(),/locked/);assert.equal(h.calls.length,0)});
test('message preparation requires a saved matching approval',async()=>{const h=harness();await assert.rejects(()=>h.adapter.prepareMessage(),/Approve/);h.set({...base(),approvalCurrent:true,quoteApproval:{fingerprint:'new'}});h.save({...base(),quoteApproval:{fingerprint:'old'}});await assert.rejects(()=>h.adapter.prepareMessage(),/Save/);assert.equal(h.calls.length,0)});
test('handoff is deliberate, current and separate from sent evidence',async()=>{const h=harness(),s={...base(),approvalCurrent:true,quoteApproval:{fingerprint:'fp1'},messagePrepared:true,messageCurrent:true};h.set(s);h.save(structuredClone(s));await h.adapter.prepareHandoff('email');assert.equal(h.adapter.read().handoffEvidence.channel,'email');assert.equal(h.adapter.read().confirmation??'No','No');await h.adapter.recordSent();assert.equal(h.adapter.read().quoteStatus,'Quote sent / waiting customer');assert.equal(h.adapter.read().confirmation,'Yes')});
test('customer acceptance requires saved sent evidence and current message',async()=>{const h=harness();const s={...base(),approvalCurrent:true,quoteApproval:{fingerprint:'fp1'},quoteStatus:'Quote sent / waiting customer',messageCurrent:true};h.set(s);h.save({...s,confirmation:'No'});await assert.rejects(()=>h.adapter.recordAcceptance(),/actual customer message/);h.save({...s,confirmation:'Yes'});h.set({...s,messageCurrent:false});await assert.rejects(()=>h.adapter.recordAcceptance(),/current/);h.set(s);await h.adapter.recordAcceptance();assert.equal(h.adapter.read().acceptedSnapshot.total,80);assert.deepEqual(h.calls,['recordAcceptance'])});
test('conversion waits for saved acceptance, preserves source and requires separate save',async()=>{const h=harness(),accepted={...base(),acceptedSnapshot:{total:80,quoteRef:'Q-1'}};h.set(accepted);await assert.rejects(()=>h.adapter.convert(),/finish saving/);h.save(structuredClone(accepted));await h.adapter.convert();assert.equal(h.adapter.read().sourceQuoteId,'Q-1');assert.equal(h.calls.includes('saveConvertedOrder'),false);await h.adapter.saveConvertedOrder();assert.equal(h.adapter.list()[0].sourceQuoteId,'Q-1')});
test('a second conversion is blocked before reaching the engine',async()=>{const h=harness();h.set({...base(),acceptedSnapshot:{total:80},convertedOrderId:'O-1'});await assert.rejects(()=>h.adapter.convert(),/already converted/);assert.equal(h.calls.length,0)});
test('failed authority operation cannot be reported as a success',async()=>{const state={...base(),approvalCurrent:true,quoteApproval:{fingerprint:'fp1'}};const saved={...state,confirmation:'No'};const adapter=createQuoteDomainAdapter({read:()=>state,readSaved:()=>saved,list:()=>[saved],command:async()=>true});await assert.rejects(()=>adapter.prepareMessage(),/did not confirm/);assert.equal(adapter.busy,false)});
test('the actual protected source retains commercial, revision and message guards',()=>{const html=fs.readFileSync('finance-operator-layout-review/index.html','utf8');const source=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]).join('\n');new vm.Script(source);for(const fn of ['approveCurrentQuote','markCurrentQuoteAccepted','convertCurrentQuoteToLive','startSendQuoteWorkflow','saveOrderNow','claimSharedOrderForEdit'])assert.match(source,new RegExp('function\\s+'+fn+'\\s*\\('));for(const field of ['acceptedSnapshot','commercialFingerprint','customerMessageDependencyFingerprint','auditHistory','sourceQuoteId','convertedOrderId'])assert.match(source,new RegExp(field));const adapter=fs.readFileSync('finance-operator-v2-job-ready-quote-proof/quote-domain-adapter.js','utf8');assert.doesNotMatch(adapter,/PRODUCT_RULES|priceTier\s*=|stock\s*\[|quickQuoteUpdate/)});
test('the mounted port is isolated and waits for engine persistence',()=>{const port=fs.readFileSync('finance-operator-v2-job-ready-quote-proof/quote-engine-port.js','utf8');assert.match(port,/connect-src 'none'/);assert.match(port,/PX_FINANCE_CONFIG=\{\}/);assert.match(port,/await waitFor\(\(\)=>\{const o=saved\(current\.id\)/);assert.match(port,/saved\(source\)\?\.convertedOrderId===live/);assert.match(port,/liveOrderSaved=!isQuote/);assert.doesNotMatch(port,/PRODUCT_RULES\s*=|COMMERCIAL_AUTHORITY_VERSION\s*=/)});
test('stale commercial authority and client-supplied prices remain fail-closed',()=>{const edge=fs.readFileSync('supabase/functions/submit-request/index.ts','utf8');const contract=fs.readFileSync('supabase/functions/submit-request/commercial-contract.mjs','utf8');assert.match(edge,/submittedVersion !== authorityVersion/);assert.match(contract,/CLIENT_COMMERCIAL_FIELDS/);assert.match(contract,/throw new HttpError\(409, "Product information has changed/);assert.match(contract,/active_for_new_request !== true/)});
test('shared conflicts and Finance role boundaries remain fail-closed',()=>{const source=fs.readFileSync('finance-operator-layout-review/index.html','utf8');const batch3=fs.readFileSync('finance-operator-layout-review/r5h-batch3.js','utf8');const batch4=fs.readFileSync('finance-operator-layout-review/r5h-batch4.js','utf8');const pricing=fs.readFileSync('supabase/migrations/20260817183000_commercial_pricing_review_v45g.sql','utf8');assert.match(source,/\['admin','finance'\]\.includes\(p\.role\)/);assert.match(source,/if\(current\.cloudReadOnly\).*return false/);assert.match(batch3,/cloudConflictState='remote_changed'/);assert.match(batch3,/Your local copy has been preserved; nothing was discarded\./);assert.match(batch4,/current\.cloudReadOnly=true/);assert.match(pricing,/p\.role in \('admin', 'finance'\)/)});
