import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
const path=new URL('../../finance-operator-v2-job-ready-quote-proof/payment-module.js',import.meta.url);
const source=readFileSync(path,'utf8');
const {createPaymentTask}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
class FormDataStub{constructor(form){this.values=form.values;}*[Symbol.iterator](){yield* Object.entries(this.values);}}
globalThis.FormData=FormDataStub;
function harness(){const nodes=new Map();const listeners={};const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',value:'',checked:false,dataset:{},focus(){}});return nodes.get(id);};const root={classList:{add(){}},innerHTML:'',querySelector(sel){return node(sel);},contains(){return true;},addEventListener(type,fn){listeners[type]=fn;}};let last;const task=createPaymentTask({onChange:s=>last=s});task.mount(root);const click=(action,fields={})=>{Object.assign(node('#pm-bank-check'),{checked:!!fields.bank});Object.assign(node('#pm-final-check'),{checked:!!fields.final});node('#pm-review-note').value=fields.note||'';listeners.click({target:{closest(){return {dataset:{pm:action}};}}});};const submit=(kind,values)=>{const form={dataset:{pmForm:kind},values};listeners.submit({target:{closest(){return form;}},preventDefault(){}});};return {task,click,submit,node,get snapshot(){return last;}};}
const evidence=(amount,reference,date='2026-09-08')=>({amount,reference,date,note:''});
test('reported payment never increases received money',()=>{const h=harness();h.click('report');h.submit('report',evidence('80.00','CUSTOMER-CLAIM'));assert.equal(h.snapshot.received,0);assert.equal(h.snapshot.remaining,8000);assert.equal(h.snapshot.status,'Payment reported');assert.equal(h.task.getState().reports.length,1);assert.equal(h.task.getState().entries.length,0);});
test('evidence is pending until an independent bank check',()=>{const h=harness();h.click('entry');h.submit('entry',evidence('30.00','BANK-030'));assert.equal(h.snapshot.received,0);assert.equal(h.snapshot.pending,3000);h.click('review:1');h.click('verify');assert.equal(h.snapshot.received,0);assert.match(h.node('#pm-work').innerHTML,/Confirm the independent bank check first/);h.click('verify',{bank:true});assert.equal(h.snapshot.received,3000);assert.equal(h.snapshot.remaining,5000);assert.equal(h.snapshot.status,'Part paid');});
test('pending evidence blocks overpayment and duplicate bank references',()=>{const h=harness();h.click('entry');h.submit('entry',evidence('30.00','BANK-030'));h.click('entry');h.submit('entry',evidence('60.00','BANK-060'));assert.equal(h.task.getState().entries.length,1);assert.match(h.node('#pm-work').innerHTML,/exceeds the balance/);h.click('entry');h.submit('entry',evidence('50.00','BANK-030'));assert.equal(h.task.getState().entries.length,1);assert.match(h.node('#pm-work').innerHTML,/already recorded/);});
test('rejection requires a reason and releases the pending amount',()=>{const h=harness();h.click('entry');h.submit('entry',evidence('80.00','BANK-BAD'));h.click('review:1');h.click('reject');assert.equal(h.snapshot.pending,8000);h.click('reject',{note:'Reference did not match bank record'});assert.equal(h.snapshot.pending,0);assert.equal(h.snapshot.received,0);assert.equal(h.task.getState().entries[0].status,'rejected');});
test('partial payments reconcile only after the full accepted total is confirmed',()=>{const h=harness();h.click('entry');h.submit('entry',evidence('30.00','BANK-030'));h.click('review:1');h.click('verify',{bank:true});h.click('entry');h.submit('entry',evidence('50.00','BANK-050'));h.click('review:2');h.click('verify',{bank:true});assert.equal(h.snapshot.received,8000);assert.equal(h.snapshot.remaining,0);assert.equal(h.snapshot.confirmed,false);h.click('reconcile');h.click('finish');assert.equal(h.snapshot.confirmed,false);h.click('finish',{final:true});assert.equal(h.snapshot.confirmed,true);assert.equal(h.snapshot.status,'Received');assert.equal(h.task.getState().entries.length,2);});
test('fixtures remain isolated and reset restores an empty payment',()=>{const h=harness();h.task.scenario('partial');assert.equal(h.snapshot.received,3000);h.task.scenario('complete');assert.equal(h.snapshot.confirmed,true);h.task.reset();assert.equal(h.snapshot.received,0);assert.equal(h.snapshot.confirmed,false);assert.equal(h.task.getState().entries.length,0);});
test('module is isolated from production writes and has no bank connection',()=>{assert.doesNotMatch(source,/fetch\s*\(|XMLHttpRequest|supabase\.|sendBeacon\s*\(/);assert.match(source,/No Finance or bank writes|No bank connection, production storage|Demo records only/);});